import { PoolConfig } from "../components/Common/types/common.types";

export const LOCALES: string[] = ["en", "es", "pt", "ar"];

export const INFURA_GATEWAY: string = "https://thedial.infura-ipfs.io";
export const INFURA_GATEWAY_INTERNAL: string =
  "https://digitalax.xyz/api/infura/";

export const CHROMADIN: `0x${string}` =
  "0x16a362A10C1f6Bc0565C8fFAd298f1c2761630C5";

export const MONA: { eth: string; poly: string; lens: string } = {
  eth: "0x275f5Ad03be0Fa221B4C6649B8AeE09a42D9412A",
  poly: "0x6968105460f67c3bf751be7c15f92f5286fd0ce5",
  lens: "0x28547B5b6B405A1444A17694AC84aa2d6A03b3Bd",
};

export const PANEL_KEY: { [key: number]: string } = {
  0: "runtime",
  1: "deLoom",
  2: "Quiltoide",
  3: "poolSearch",
  4: "recuts",
};

export const BADGE_RECORDS = [
  {
    name: "gpu",
    image: "Qmdt7sijfg9asAHbcJLvFCieaspxosAV9QJskT2rKPHhNz",
    color: "record1",
  },
  {
    name: "collector",
    image: "Qmd2q57GCci7DV8HTdT66D4bqhuyptHYehYa5UnxfcTjuA",
    color: "record2",
  },
  {
    name: "critique",
    image: "QmUGp8UDeARbmqCjHJnGP72q7GAddiKcj2NdTJqbM4DNBY",
    color: "record3",
  },
  {
    name: "creative",
    image: "QmedQ8w5WjSX5aKqdLAKywuwsThpR1dDb6bnLynpH4bh5d",
    color: "record4",
  },
  {
    name: "fashion",
    image: "QmeHxDgvWG4gXpUc5oBCPnkHFYRcswffaUEqyMRwiUJJkT",
    color: "record5",
  },
  {
    name: "synth",
    image: "QmWa2nzAUy9dn6xZHE4kFeX2A3gNsNL2oh76gmxypGMqNt",
    color: "record6",
  },
  {
    name: "generative",
    image: "QmPWirsvrp1arB2QKH2uMbnjrenEsWXDsBSBSa83jLSKqG",
    color: "record7",
  },
  {
    name: "stunning",
    image: "QmR9qx5CxbSbTDMNyUXCsEZd49aB8mK4cXcWNpKCPuAwdA",
    color: "record8",
  },
  {
    name: "viral",
    image: "QmV9vLf5mu3XGZ5ZdbKg765Z2b7F1WkEFGSEiwreaHsDj6",
    color: "record9",
  },
  {
    name: "draft_master",
    image: "QmeFv3m9SG7ELeoHwLMaFyCtLne68BpMkKYMjzqShaGjfn",
    color: "record10",
  },
  {
    name: "hot",
    image: "Qmc7QWS3PfRQBjqQrTRHAvo716PLENsvRVMADchbC6eePs",
    color: "record11",
  },
  {
    name: "trending",
    image: "Qmejk9taYW3qY98GMEhu9NjFbQDfQhM6549a5agE4foM3T",
    color: "record12",
  },
  {
    name: "merchant",
    image: "QmaJ4w7MWYmz2GCe6aSjesa5HEtgxLrDZuLcqu3rmpCMFC",
    color: "record13",
  },
  {
    name: "top_weekly",
    image: "QmXLaMBkLNyBey8fQ9fCrsQdMkezS3E4jM4CEpNhy4Jaid",
    color: "record14",
  },
  {
    name: "top_monthly",
    image: "QmQX9Y77E5kPVoipczoUUR2jqeYsAcnTBRCH4wKTsewoMU",
    color: "record15",
  },
  {
    name: "innovator",
    image: "QmbA48L728fSqPDnC48GG4UYHdVGzsLriowFsRoSLHV54p",
    color: "record16",
  },
  {
    name: "visionary",
    image: "Qmc1pxgedArguNpjKAXmWhJHDpnwELBC7SRPbi1fn831Ev",
    color: "record17",
  },
  {
    name: "pioneer",
    image: "QmTvEJGC92Ec2uzNBoJcQqN5DmJ8ppfMTcQqV3D1y4CXh5",
    color: "record18",
  },
  {
    name: "builder",
    image: "QmeLCCxARTVfpSB1PX1kQCvHg3egD649L39j1SeYCDu7MU",
    color: "record19",
  },
  {
    name: "catalyst",
    image: "QmdjquvPR3j8xnfhT7Gt2QjspKgWVyG9hxodvqqFTSWpp7",
    color: "record20",
  },
  {
    name: "maverick",
    image: "QmNVojSQ5NmrVvdWLMZmMpuMkvPtv854Xu4zn33pGvTxnu",
    color: "record21",
  },
  {
    name: "disruptor",
    image: "QmRYqHi8pshFk2VaeEpEWFtJsyjQCy18CcPVNhHK5kTJwY",
    color: "record22",
  },
  {
    name: "curator_pro",
    image: "QmWBoyMqxNfjHvroX19iHA5wq85Kbvg4AF7T3HASpwBeGS",
    color: "record23",
  },
  {
    name: "architect",
    image: "QmWJVF1ez8wffZV7Gz4A1BZDs87FVHLXVkeaS8615sL4hT",
    color: "record24",
  },
  {
    name: "legend",
    image: "QmTbz6CKqx5m32BRhW1Kf9JxVHDwYov7xxm4pKSMAjZGGx",
    color: "record25",
  },
  {
    name: "elite",
    image: "Qmc5MEdCHbCaQp9JjzwAzd4aEKToHqeHy65pqsUJCo5c9d",
    color: "record26",
  },
  {
    name: "champion",
    image: "QmP2eVT8z3jDfikPVmZoGAhk8qWs6qwtSEwMzc4Mht98fE",
    color: "record27",
  },
  {
    name: "oracle",
    image: "QmbXTFYEpiEGFFQdPnvWTGbXPtSwZ6sfWM73P7db67dfV5",
    color: "record28",
  },
  {
    name: "mystic",
    image: "QmNXkEoj6oCTURV31sVfxsYEGdU9b2bRyJWTHAMktzpyvp",
    color: "record29",
  },
  {
    name: "sage",
    image: "QmbnsKepJHu3i4FLcygcmEbEd5h3a9hgbuq8QcCeN7aE98",
    color: "record30",
  },
];

export const PANELES: string[] = [
  "QmRUztxbrNETu85M3o9RoyqEKBeGEeV5kT5K8hberNTHw7",
  "QmfG4dGSYrtv2hCUnURNvfKyk92ZwVJoG9wiMvtjhVQm8y",
  "QmS3dGNFY7JuqGaQcuZnmSqTZxsKBHjsKfCySEMxjLduQc",
  "QmVvtK2x9TQJzqfAnQPUKapQKVohXAjUrTrpry8TWZMhei",
  "QmdptnVYNSsfrg7s39y4QetAFtcVsrNRR5eH7ayifS1j79",
];

export const POOLS: PoolConfig[] = [
  {
    id: "eth-genesis-v1",
    nameKey: "ethGenesisV1",
    name: "Genesis V1 Staking",
    shortName: "Genesis V1",
    description: "Ethereum Genesis pool",
    chainId: 1,
    chainLabel: "Ethereum",
    stakingAddress: "0xa202D5B0892f2981bA86C981884cebA49B8AE096",
    kind: "nft",
    rewardLabel: "MONA",
    subgraphKey: "eth",
  },
  {
    id: "eth-parent",
    nameKey: "ethParent",
    name: "721 NFT Staking",
    shortName: "Parent 721",
    description: "Ethereum 721 Garment pool",
    chainId: 1,
    chainLabel: "Ethereum",
    stakingAddress: "0xc802912c379a1EF995a23c07346bD8373049fa39",
    kind: "nft",
    rewardLabel: "MONA",
    subgraphKey: "eth",
  },
  {
    id: "poly-mona",
    nameKey: "polyMona",
    name: "MONA / LP Staking",
    shortName: "MONA / LP",
    description: "Polygon MONA + LP pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0xF795c2abB0E7A56A0C011993C37A51626756B4BD",
    kind: "mona",
    rewardLabel: "MONA + extra ERC20s",
    subgraphKey: "poly",
  },
  {
    id: "poly-nft",
    nameKey: "polyNft",
    name: "NFT Staking",
    shortName: "NFT Staking",
    description: "Polygon main NFT pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0xd80eeB5aFfd3C419f2Cb05477372778862D26757",
    kind: "nft",
    rewardLabel: "MONA + extra ERC20s",
    subgraphKey: "poly",
  },
  {
    id: "poly-nft-old",
    nameKey: "polyNftOld",
    name: "NFT Staking (Legacy)",
    shortName: "NFT Legacy",
    description: "Polygon legacy pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0xa7cf890C70817D57ea355C2F4B4BF23B064D91F7",
    kind: "nft",
    rewardLabel: "MONA",
    subgraphKey: "poly",
  },
  {
    id: "poly-genesis-v2",
    nameKey: "polyGenesisV2",
    name: "Genesis V2 Staking",
    shortName: "Genesis V2",
    description: "Polygon Genesis pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0x6Afda2712225F950c93e7fd7C807BDE28f1E65A5",
    kind: "nft",
    rewardLabel: "MONA",
    subgraphKey: "poly",
  },
  {
    id: "poly-w3f",
    nameKey: "polyW3f",
    name: "GDN V1 ERC20",
    shortName: "GDN V1",
    description: "Polygon GDN V1 ERC20 pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0x8Df6c229B3645F7440C2902bAa135635AbB845EB",
    kind: "mona",
    rewardLabel: "MONA + extra ERC20s",
    subgraphKey: "poly",
  },
  {
    id: "poly-gdn",
    nameKey: "polyGdn",
    name: "Pattern House I Staking",
    shortName: "Pattern House I",
    description: "Polygon Pattern House I pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0x2E4ae1f8E1463f450e9B01F20cee1590Bff4E1fC",
    kind: "nft",
    rewardLabel: "DECO + extras",
    subgraphKey: "poly",
  },
  {
    id: "poly-pode-guild",
    nameKey: "polyPodeGuild",
    name: "PODE Guild Staking",
    shortName: "PODE Guild",
    description: "Polygon PODE guild pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0x8CaF6ceaA682F0569d5Ee83F5022bf1cD6705395",
    kind: "nft",
    rewardLabel: "DECO + extras",
    subgraphKey: "poly",
  },
  {
    id: "poly-pode-guild-whitelist",
    nameKey: "polyPodeGuildWhitelist",
    name: "PODE Guild Whitelist Staking",
    shortName: "PODE Guild WL",
    description: "Polygon PODE guild whitelisted pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0x16218D677e160DDfb398D26508e5f6fB44c06f28",
    kind: "nft",
    rewardLabel: "DECO + extras",
    subgraphKey: "poly",
  },
  {
    id: "poly-realm",
    nameKey: "polyRealm",
    name: "V1 Realm Staking",
    shortName: "V1 Realm",
    description: "Polygon V1 Realm pool",
    chainId: 137,
    chainLabel: "Polygon",
    stakingAddress: "0xE8775b2CA0b4EBBf00AfA9c2bF55532D431C5653",
    kind: "nft",
    rewardLabel: "DECO + extras",
    subgraphKey: "poly",
  },
];

export const TOPICS: string[] = [
  "in the style of",
  "genre",
  "format",
  "colors",
  "lighting",
  "engines",
  "design tools",
  "techniques",
  "fashion",
  "equipment",
  "descriptive",
];

export const STYLE: string[] = [
  "pixel expressionism",
  "neo precisionism",
  "web brutalism",
  "greg",
  "an inpunk graphic novel",
  "super sonic couture",
  "bushwick street style",
  "alphonse mucha",
];

export const GENRE: string[] = [
  "aetherpunk",
  "anime",
  "bricolage",
  "cassette futurism",
  "cottagecore",
  "cyberpunk",
  "dark academia",
  "digicore",
  "fantasy",
  "futuristic",
  "glitch art",
  " retro",
  " sci-fi",
  " solarpunk",
  "spacewave",
  "synthwave",
  "vaporwave",
];

export const FORMAT: string[] = [
  "2d",
  "3d",
  "apparel",
  "AR",
  "architecture",
  "digital",
  "film",
  "magazine",
  "oil on canvas",
  "photography",
  "print",
  "projection",
  "VR",
];

export const COLORS: string[] = [
  "analogous colors",
  "angular gradient",
  "black and white",
  "color graded",
  "complementary colors",
  "contrasting colors",
  "holographic",
  "iridescent",
  "linear gradient",
  "metallic colors",
  "monochromatic",
  "pastels",
  "radial gradient",
  "tetradic colors",
  "triadic colors",
];

export const LIGHTNING: string[] = [
  "ambient",
  "anamorphic",
  "atmospheric",
  "backlighting",
  "bounce",
  "butterfly",
  "cinematic",
  "diffuse",
  "directional",
  "dramatic",
  "flat",
  "halo",
  "hard",
  "loop",
  "omni",
  "practcal",
  "rembrandt",
  "side",
  "soft",
  "split",
  "spotlight",
];

export const ENGINES: string[] = [
  "autocad",
  "blender",
  "cinema4d",
  "krita",
  "maya",
  "octane",
  "photoshop",
  "unity",
  "unreal",
  "zbrush",
];

export const DESIGNTOOLS: string[] = [
  "aesprite",
  "affinity",
  "after effects",
  "figma",
  "illustrator",
  "photomosh",
  "photoshop",
  "playscii",
  "premier pro",
  "procreate",
  "sketch",
  "unsplash",
];

export const TECHNIQUES: string[] = [
  "pixel expressionism",
  "neo precisionism",
  "web brutalism",
  "greg",
  "an inpunk graphic novel",
  "super sonic couture",
  "bushwick street style",
  "alphonse mucha",
];

export const FASHION: string[] = [
  "80s",
  "90s",
  "00s",
  "athleisure",
  "bohemian / boho chic",
  "business casual",
  "chic",
  "classic",
  "cyberpunk",
  "digicore",
  "grunge",
  "minimalist",
  "patchwork",
  "punk",
  "retro",
  "streetwear",
  "techwear",
  "vintage",
];

export const EQUIPMENT: string[] = [
  "ansible",
  "beeper",
  "chip fabricator",
  "computer",
  "loom",
  "mobile phone",
  "oscilloscope",
  "printer",
  "typewriter",
  "radio",
  "satellite",
  "silkscreen",
  "wristwatch",
];

export const DESCRIPTIVE: string[] = [
  "biographical",
  "drama",
  "essay",
  "fable",
  "fairy tale",
  "fantasy",
  "fiction",
  "folklore",
  "historical fiction",
  "horror",
  "humor",
  "legend",
  "magical realism",
  "mystery",
  "mythology",
  "narrative",
  "nonfiction",
  "poetry",
  "science fiction",
  "speech",
];

export const PRESETS: string[] = [
  "vintage americana",
  "Neo-Tokyo",
  "product design by Dieter Rams and by Jony Ives",
  "techwear",
  "liquid gold",
  "trouser skirt and faux pixelated top",
  "Lower East Side golden hour sunset",
  "patchwork streetwear",
  "1970s Andor opening theme",
  "Teenage Engineering minimalissimo",
  "solarpunk",
  "AI Art profile photo",
  "10k NFT collection",
  "24/7 livestream cover art",
  "rolltop canvas bag",
  "revolutionary poster art",
  "lens culinaris cyberpunk oil on canvas",
  "stylish streetwear in a convenience store",
  "ultra detailed vector floral illustration",
  "ray tracing reflections",
  "pen and ink",
  "hand-drawn watercolor",
  "flowers everywhere",
  "huge savage rabbit monster",
  "enigmatic",
  "graffiti tag wall background",
  "magical fantasy atmosphere",
  "lots of boats",
  "fashion magazine",
  "astronaut in a garden on a spring day",
  "inspired by byte magazine cover art",
  "space and earth alone forever",
  "cyber economics",
  "surreal time machine designed by dieter rams",
  "vintage shoes silhouette photoshoot film grading",
  "chaotic arcade at night",
  "eastman kodak color negative film 5251",
  "shibuya fashion",
  "retro anime teenager wearing hoodie",
  "chaotic hand drawing colored sketch illustration",
  "infantile graphics interior abandoned factory",
  "environmental wide shot of a crowded underground market",
  "hiding within a crowd of people",
  "messy artist's workshop",
  "personal robot weaver",
  "Interior of a photojournalist's workshop",
  "abstract halftone pattern and 3d shirt mockup",
  "augmented reality hoodie design",
  "chromatic aberration",
  "solid black pillar inside an underground lake",
  "behind the scenes on the set of a claymation movie",
  "drawing a keyframe for a new anime",
  "👩‍🚀🍄🏢🌿🍒, surrealism, architecture",
];

export const TOKEN_ADDRESSES = {
  eth: {
    mona: MONA.eth,
    genesisV1: "0x89505d2a27b7e8ac56252081d721ecd525e4241e",
    podePortal: "0x87c3C6B9C917B1732f13d36d6938E4f8802f7c7E",
  },
  poly: {
    mona: MONA.poly,
    genesisV2: "0x2543d997e766af463e2b11bd7ee3e6d722bb1d9b",
    podeV2: "0x6d4d0b9eacd6197b31bec250c0ad6cec98f8b83f",
    deco: "0x200f9621cbce6ed740071ba34fde85ee03f2e113",
    dlta: "0x0a5ef416fb5117f9f832f7f308320a6071f257c9",
  },
  lens: {
    mona: MONA.lens,
  },
};

export const idiomaAIndice: { [key in Idiomas]: number } = {
  ["en"]: 0,
  ["es"]: 1,
  ["ar"]: 2,
  ["pt"]: 3,
};

export enum Idiomas {
  Ingles = "en",
  Español = "es",
  Árabe = "ar",
  Portugués = "pt",
}

export const indiceAIdioma: { [key in number]: string } = {
  [0]: "en",
  [1]: "es",
  [2]: "ar",
  [3]: "pt",
};
